export const API_ENDPOINTS = {
  auth: {
    login: '/athletes/login',
    googleLogin: '/athletes/auth/google',
    registerAthlete: '/athletes/register',
    createPlayerProfile: '/player-profiles',
    refresh: '/athletes/auth/refresh',
    logout: '/athletes/auth/logout',
    passwordResetRequest: '/athletes/password-reset/request',
    passwordResetConfirm: '/athletes/password-reset/confirm',
  },
  matches: {
    base: '/matches',
    orchestrated: '/matches/orchestrated',
    byPlayer: '/matches/by-player',
    byPlayerOrCreator: '/matches/by-player-or-creator',
    join: '/matches/join',
    events: '/matches/events',
    aiSummary: '/matches',
  },
  ratings: {
    base: '/ratings',
    leaderboard: '/ratings/leaderboard',
    initializeBase: '/ratings/player',
  },
  users: {
    athletes: '/athletes',
    playerProfiles: '/player-profiles',
    playerProfileAchievements: '/player-profiles',
    playerProfilePositions: '/player-profiles/positions',
    playerProfileTrustScore: '/player-profiles/trust-score',
    positions: '/positions',
  },
  teams: {
    base: '/teams',
    byCreator: '/teams/by-creator',
    byPlayer: '/teams/by-player',
    uploadLogo: '/teams/logo',
  },
  fields: {
    base: '/fields',
  },
  social: {
    base: '/social',
    friendships: '/social/friendships',
    friendshipRequests: '/social/friendships/requests',
    teamInvites: '/social/team-invites',
    matchInvites: '/social/match-invites',
    matchInvitesBatch: '/social/match-invites/batch',
    matchInvitesBatchDetailed: '/social/match-invites/batch/detailed',
    matchInvitesByMatch: '/social/match-invites/by-match',
    notifications: '/social/notifications',
    notificationUnreadCount: '/social/notifications/unread-count',
    pushTokens: '/social/notifications/push-tokens',
    reminders: '/social/notifications/reminders/forms',
    searchPlayers: '/social/players/search',
  },
} as const;
